# Default values for Transmission.

image:
  repository: bohitigaming/crushftp
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

service:
  port:
    port: 8080


env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

  torrentblackhole:
    enabled: false
    emptyDir: false
    mountPath: /downloads
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""


## TrueCharts Values






appVolumeMounts:
  config:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/config"
  downloads:
    enabled: true
    emptyDir: true
    setPermissions: true
    mountPath: "/downloads"


appAdditionalServicesEnabled: true
appAdditionalServices:
  tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 9022
      name: ftp-tcp
      protocol: TCP
      targetPort: 9022
  udp:
    enabled: true
    type: ClusterIP
    port:
      port: 9022
      name: ftp-udp
      protocol: UDP
      targetPort: 9022
