# Default values for Transmission

image:
  repository: bohitigaming/crushftp
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

service:
  port:
    port: 8080

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

## TrueCharts Values


#appVolumeMounts:
#  config:
#    enabled: true
#    emptyDir: false
#    datasetName: "config"
#  downloads:
#    enabled: true
#    emptyDir: false
#    datasetName: "downloads"