# Default values for Transmission

image:
  repository: bohitigaming/crushftp
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

service:
  port:
    port: 8080

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

## TrueCharts Values
#Transmission Default Configuration
crushftp-config:
 CRUSH_ADMIN_USER: crushadmin
 CRUSH_ADMIN_PASSWORD: crushadmin
 CRUSH_ADMIN_PROTOCOL: http
 CRUSH_ADMIN_PORT : 8080


#appVolumeMounts:
#  config:
#    enabled: true
#    emptyDir: false
#    datasetName: "config"
#  downloads:
#    enabled: true
#    emptyDir: false
#    datasetName: "downloads"


appAdditionalServicesEnabled: true
appAdditionalServices:
  tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 51413
      name: ftp-tcp
      protocol: TCP
      targetPort: 51413
      nodePort: 51413
  udp:
    enabled: true
    type: ClusterIP
    port:
      port: 9022
      name: bittorrent-udp
      protocol: UDP
      targetPort: 9022
      nodePort: 9022