# Default values for Transmission

image:
  repository: linuxserver/transmission
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

service:
  port:
    port: 9091

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001

persistence:
  config:
    enabled: false
    emptyDir: false

## TrueCharts Values




#appVolumeMounts:
#  config:
#    enabled: true
#    emptyDir: false
#    datasetName: "config"
#  downloads:
#    enabled: true
#    emptyDir: false
#    datasetName: "downloads"


appAdditionalServicesEnabled: true
appAdditionalServices:
  tcp:
    enabled: true
    type: ClusterIP
    port:
      port: 51413
      name: bittorrent-tcp
      protocol: TCP
      targetPort: 51413
      nodePort: 51413
  udp:
    enabled: true
    type: ClusterIP
    port:
      port: 51413
      name: bittorrent-udp
      protocol: UDP
      targetPort: 51413
      nodePort: 51413
securityContext:
       capabilities:
         add:
           - NET_ADMIN   