apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
type: Opaque
data:
 CRUSH_ADMIN_USER: {{ .Values.crushftpconfig.CRUSH_ADMIN_USER | b64enc | quote }}
  {{ if .Values.crushftpconfig.CRUSH_ADMIN_PASSWORD }}
 CRUSH_ADMIN_PASSWORD: {{ .Values.crushftpconfig.CRUSH_ADMIN_PASSWORD | b64enc | quote }}
  {{ else }}
 CRUSH_ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}