{{ $svc := .Values.crushftpServiceTCP }}
{{ $ports := list }}
{{ $ports = mustAppend $ports (dict "name" "crushftp" "port" $svc.port "nodePort" $svc.port "targetPort" "crushftp") }}
{{ $ports = mustAppend $ports (dict "name" "ftp-sftp" "port" 9022 "targetPort" "crushftp") }}
{{ $ports = mustAppend $ports (dict "name" "ftp-ftp-tcp" "port" 9021 "targetPort" "crushftp") }}
{{ $params := . }}
{{ $_ := set $params "commonService" (dict "ports" $ports ) }}
{{ if .Values.hostNetwork }}
{{ $_ := set $params.commonService "nameSuffix" "tcp-cluster-ip" }}
{{ $_1 := set $params.commonService "type" "ClusterIP" }}
{{ else }}
{{ $_ := set $params.commonService "nameSuffix" "tcp" }}
{{ $_1 := set $params.commonService "type" "NodePort" }}
{{ end }}
{{ include "common.classes.service" $params }}
